Hw04 lru cache
ruknez/OTUS_GOLANG_hw pull request #4
Opened 2021-07-13 13:06 UTC by ruknez

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2021-07-18 08:04 UTC, kulti requested changes
Дмитрий, спасибо за вариант решения. Мне нравится, что вы мыслите шире, чем рамки ДЗ и добавили полезные методы в Cache (Метод в List сомнительной полезности, т.к. фиксирует внутреннее представление листа. Этот тип о данных, а не о том, как их кому-то показывать). И что задаетесь вопросами публичности/приватности 👍 

Похоже в методе Remove есть ошибка (пометил этот дискашен ракетой). Все остальное косметика. Также нужно поработать с тестами. Сейчас я не знаю, что они тестируют. В задании (и чек-листе) прописано, какие тесты на кэш ожидаются. Нужно добавить хотя бы их. Иначе не хватит баллов до зачета.

2021-07-18 08:04 UTC, kulti commented on hw04_lru_cache/list.go
> +	prev  *ListItem // зачем их делать public ???
Зачем их делать private? И почему к Value такого вопроса нет?

Лично я бы сделал все приватным и добавил публичные методы-геттеры. Но и вариант структуры с публичными полями тоже зачастую нормальное решение.

Это не архитектурное ДЗ, поэтому здесь это вообще неважно :)

2021-07-18 08:04 UTC, kulti commented on hw04_lru_cache/list.go
> +	len    uint64
Зачем uint64? Потом происходит небезопасный каст к int.

2021-07-18 08:04 UTC, kulti commented on hw04_lru_cache/list.go
> +	newListItem.prev = nil
nil — это zero-value для указателя, можно отдельно не прописывать.

2021-07-18 08:04 UTC, kulti commented on hw04_lru_cache/list.go
> +		return
Что это за случай? Кажется, такого не может быть по условиям ДЗ.

2021-07-18 08:04 UTC, kulti commented on hw04_lru_cache/list.go
> +		current = nil
Зачем тут присваивается nil? Это же ничего не дает.

2021-07-18 08:04 UTC, kulti commented on hw04_lru_cache/list.go
> +		ls.header = current.next
Чему теперь равен `ls.header.prev`?

2021-07-18 08:04 UTC, kulti commented on hw04_lru_cache/list.go
> +	}
Эти две ветки ифа различаются парой строк (на самом деле одной по сути). Предлагаю упростить и не дублировать.

2021-07-18 08:04 UTC, kulti commented on hw04_lru_cache/list.go
> +func (ls *list) PrintList(s int) {
Не понял, зачем этот метод. Не вижу, чтобы он использовался.

2021-07-18 08:04 UTC, kulti commented on hw04_lru_cache/cache_test.go
> +	t.Run("MyTests", func(t *testing.T) {
Название теста должно отражать, что он тестирует. Не могу знать, что вы хотели протестировать этим кодом.

2021-07-18 08:04 UTC, kulti commented on hw04_lru_cache/cache.go
> +	} else if lru.queue.Len() >= lru.capacity {
Думаю, лучше будет читаться отдельный if (без else), т.к. в предыдущей ветке return. Вроде, линтер должен такие штуки отлавливать.

2021-07-21 11:23 UTC, ruknez commented on hw04_lru_cache/list.go
> +	prev  *ListItem // зачем их делать public ???
Идея была такая что Value это основа листочка. А указатели на следующий и предыдущи уже реализация которая не нужна пользователю. Заменил на Getvalue. Вопрос не в том что архитектурное дз или нет, а в  том что бы достаточно правильно сделать все и стремиться к некому максимализму....

2021-07-21 11:23 UTC, ruknez commented on hw04_lru_cache/list.go
> +	newListItem.prev = nil
Да просто что бы понимать что не забыть ничего указать ставлю явно nil

2021-07-21 11:23 UTC, ruknez commented on hw04_lru_cache/list.go
> +		return
По условиям ДЗ да гарантируется что нельзя, но в теории вообще могут передать. Но у меня в тестах есть такой случай, оставил, лишним не будет. Он же (этот case ) никому не мешает.

2021-07-21 11:24 UTC, ruknez commented on hw04_lru_cache/list.go
> +		current = nil
Для того что бы на область памяти которая выделена под ListItem никто не указывал  и сборщик мусора ее очистил.

2021-07-21 11:24 UTC, ruknez commented on hw04_lru_cache/list.go
> +		ls.header = current.next
Пофиксил

2021-07-21 11:24 UTC, ruknez commented on hw04_lru_cache/list.go
> +func (ls *list) PrintList(s int) {
Был нужен для дебага.

2021-07-21 11:24 UTC, ruknez commented on hw04_lru_cache/cache_test.go
> +	t.Run("MyTests", func(t *testing.T) {
Изменил на Work with cach потому что там идет комплексная работа с кешом

2021-07-21 11:24 UTC, ruknez commented on hw04_lru_cache/cache.go
> +	} else if lru.queue.Len() >= lru.capacity {
Пофиксил

2021-07-25 06:11 UTC, kulti commented on hw04_lru_cache/list.go
> +	prev  *ListItem // зачем их делать public ???
Это похвальное стремление. Главное, чтобы из-за этого не страдало то, что важно.

2021-07-25 06:13 UTC, kulti commented on hw04_lru_cache/list.go
> +		current = nil
Это локальная переменная. Как только выйдем из функции эта ссылка на память тоже исчезнет. И потом GC уже сможет собрать (если других ссылок нет). Поэтому это лишняя строчка и ничего полезного не делает.

2021-07-25 06:17 UTC, kulti commented on hw04_lru_cache/list.go
> +	}
В первой ветке `current` равен `ls.tail`. Значит `current.next` равен `nil`. Поэтому строчки `current.prev.next = nil` и `current.prev.next = current.next` тоже дублируются (я же написал, что на самом деле только одна строчка разная :)). И current.next = ls.header зачем-то в первом if'e осталась.

2021-07-25 06:20 UTC, kulti commented on hw04_lru_cache/list.go
> +// func (ls *list) PrintList(s int) {
Закомментированный код еще хуже. Он быстро устаревает и перестает компилироваться. Непонятно, почему его закомментировали, а не удалили. Это загрязняет код и путает будущих разработчиков.

Я бы ненужный метод просто удалил. Если считаете, что он нужен, то оставьте его.

2021-07-25 06:20 UTC, kulti commented on hw04_lru_cache/cache_test.go
> +	t.Run("MyTests", func(t *testing.T) {
Такой тест трудно понимать и поддерживать. Тест стоит делать атомарным, проверяющим что-то одно.

2021-07-25 06:22 UTC, kulti requested changes
Дмитрий, спасибо за диалог и правки.

Код немного грязноватый и не выполнен пункт «Добавлены новые юнит-тесты для кэша». Из-за этого 6/10. Это пока незачет.

2021-07-27 20:13 UTC, ruknez commented on hw04_lru_cache/list.go
> +// func (ls *list) PrintList(s int) {
Удалил

2021-07-27 20:13 UTC, ruknez commented on hw04_lru_cache/list.go
> +		current = nil
Да точно, что-то затупил

2021-07-31 16:28 UTC, kulti approved these changes
Дмитрий, спасибо за доработки.

Принято на 9/10.

Еще один балл можно получить, если добавить тест:
> на логику выталкивания давно используемых элементов

2021-08-05 06:36 UTC, ruknez commented
Добавил тест 
pushing out long-unused elements

2021-08-05 10:01 UTC, kulti approved these changes
Поднял баллы до 10 🚀

2021-08-05 13:53 UTC, merged